### ISSUE TITLE
NameError: name 'always_connected' is not defined

### ISSUE THREAD

**Issue by Danie10** [Danie10/warp-cli-gui#1]
Discovered a variable declaration issue that only appeared with the binary on a new installation, giving error:

```
Traceback (most recent call last):
  File "warp-cli-gui.py", line 298, in <module>
  File "warp-cli-gui.py", line 259, in display_aon
NameError: name 'always_connected' is not defined. Did you mean: 'always_conn_btn'?
[6587] Failed to execute script 'warp-cli-gui' due to unhandled exception!

```
Am working on diagnosing the global variable declaration which is causing this.

**Comment by Danie10** [comment]
Variables issue fixed and v1.4 source code and binary published.
